export const userActionTypes = {
    SET_ACCESS_TOKEN: "SET_ACCESS_TOKEN",
    SET_REFRESH_TOKEN: "SET_REFRESH_TOKEN",
    SET_AUTH_TOKEN: "SET_AUTH_TOKEN",
    SET_PROFILE_DATA: "SET_PROFILE_DATA",
    LOGOUT_USER: 'LOGOUT_USER',
};
